# project.toml

[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = true  # optional, preserves single vs double quotes

[tool.ruff]
# Global Ruff settings
line-length = 100
# Optional: Exclude certain files/directories
exclude = ["env/", "migrations/", "media/", "static/", ".venv/"]

[tool.ruff.lint]
# Linters to select
select = ["E", "F", "I", "UP", "B", "SIM", "ASYNC", "S", "RUF"]

# Linters to ignore
ignore = ["E501"]  # line length is handled by black

# Move per-file-ignores here under lint
per-file-ignores = { "tests/*" = ["D", "S101"], "forizec.py" = ["S603", "S607"] }