"""added ReminderTypeEnum

Revision ID: 17b34ce81d9a
Revises: 3fd916879a77
Create Date: 2025-08-25 14:01:12.139371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b34ce81d9a'
down_revision: Union[str, Sequence[str], None] = '3fd916879a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'priority',
                sa.Enum(
                    'NONE', 'TASK_DUE', 'POLICY_REVIEW', name='remindertypeenum', native_enum=False
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
